### ISSUE TITLE
Amazon Instant Video US

### ISSUE THREAD

**Issue by robotiv** [jamiees2/dnsproxy#9]
Hi,

Great project! I was looking at getting Amazon Instant Video working for the US and was wondering if you could help getting this added?

For the EU the desktop URLs are:
atv-ps-eu.amazon.com
atv-ext-eu.amazon.com

Thanks

**Comment by jamiees2** [comment]
Hi!

I am not quite sure what you would like to add this to exactly. Is this the URL for an EU specific version, or for the US? An IP lookup suggests that they are for the US, but I don't know :stuck_out_tongue_closed_eyes:

If they are EU specific, feel free to add a `proxies/proxies-eu.json` file and send a PR.
Or if it is for the US, add it to the `proxies/proxies-us.json` file and send a PR.

For help with setting it up, refer to here [proxies.json](https://github.com/jamiees2/dnsproxy/wiki/proxies.json) (I wrote this specifically for this post :wink:).

I  would reccomend using Wireshark to log all DNS queries while you load instant video, and maybe you can find some other region locked URL's. Don't add all the urls that are loaded though, only the region checking ones, as this speeds up the stream alot.

I am sorry that I cannot help much more, as i do not have an Instant Video subscription, making me unable to properly test these things. If you have any questions, just leave them in a comment here.

**Comment by chocolatebegood** [comment]
If it's the US address you want they are:
atv-ps.amazon.com
fals.atv-ps.amazon.com
atv-ext.amazon.com

**Comment by robotiv** [comment]
@chocolatebegood awesome thanks. Are there any more that are needed for other devices or is this just for getting it to work on the PC?

**Comment by chocolatebegood** [comment]
I've just tested it on my computer and iPhone. There probably is more addresses for other devices though.

**Comment by jamiees2** [comment]
Cool! I wanted to be sure that they are the addresses for the US version, because i would like for it to be possible to choose which version you want to access in the future (choosing between US and UK Netflix for example). I just checked Wikipedia and Amazon has US and UK specific versions, along with a couple more.

In any case, send me a PR with this added to `proxies-us.json` and i will accept it.

**Comment by ck-ws** [comment]
I would like to contribute the Amazon Instant Video entries, but your usage of the DNAT-flag is confusing me.
If I set dnat to false in the proxies file, it creates me DNAT hosts and dnsmasq files for these hosts, but the haproxy and iptables config is not setting up specific ports for this and is using the SNI ports. Also vice versa. If I stuck together the files with changing the options in between, it's working fine for me with the DNAT setup ;)

So should dnat in proxies be true when DNAT must be used or when SNI is working?

**Comment by jamiees2** [comment]
Hi, I'm sorry about this, I'll try to clarify better when I get home.

`dnat` should be `true` if this domain is explicitly accessed by a device
not supporting SNI.

**Comment by ck-ws** [comment]
Then probably your dnsmasq and hostsfile generators need a change since they currently create a new local IP for the SNI hosts (which is not MASQUERADED by the iptables rules, these hosts are not handled at all). Should I create a pull request for this as well?
Also I will try to check which hosts need a non-SNI entry.
As a notice to others here: The only one I currently found is atv-ps(-eu).amazon.com, which is resolved by the Fire TV, but then the IP is probably directly used (my observations using sniproxy in dockerflix).

**Comment by jamiees2** [comment]
Sure, please do :) I'm not running the DNAT setup myself, and haven't had the time to write unit tests yet.

**Comment by jamiees2** [comment]
I believe this issue can be closed now, as the proxies discussed have been added.
